const data = {
    "Я и моя семья": {
        "Личные данные": [
            "un nom --- прізвище",
            "un prénom --- ім'я",
            "un patronyme --- побатькові",
            "un sexe --- стать",
            "un âge --- вік",
            "une nationalité --- національність",
            "une citoyenneté --- громадянство",
            "une situation de famille --- сімейний стан",
            "une adresse --- адреса",
            "nombre d'enfants",
            "numéro de téléphone"
        ],
        "Члены семьи, родственники": [
            "une grand-mère --- бабушка",
            "un frère --- брат",
            "un petit-fils --- внук",
            "une petite-fille --- внучка",
            "une cousine --- двоюродная сестра",
            "un cousin --- двоюродный брат",
            "un grand-père --- дедушка",
            "une fille --- дочь",
            "un oncle --- дядя",
            "une femme --- жена",
            "une mère --- мать",
            "une belle-mère --- мачеха",
            "un mari --- муж",
            "un père --- отец",
            "un beau-père --- отчим",
            "un neveu --- племянник",
            "une nièce --- племянница",
            "une soeur --- сестра",
            "un fils --- сын",
            "une tante --- тeтя",
        ],
        "Семейное положение": [
            "une veuve --- вдова",
            "un veuf --- вдовец",
            "marié / mariéе --- женатый / замужем",
            "séparé / séparée --- проживающий отдельно / проживающая отдельно (без официального развода)",
            "divorcé / divorcéе --- разведен / разведена",
            "célibataire / célibataire --- не женат / не замужем",
            "fiancé(е) --- невеста, жених",
            "fiancé(е) --- помолвлен(а)",
        ],
        "Светский этикет": {
            "Приветствие. Знакомство. Обращение": [
                "Bonjour! --- Добрый день!/Здравствуйте!",
                "Bonjour!/Bonsoir! --- Доброе утро!/Добрый вечер!",
                "Salut! --- Привет!/Пока!",
                "Comment ça va? --- Как дела?",
                "Très bien, merci. --- Очень хорошо, спасибо.",
                "Quel est votre/ton nom? --- Как вас/тебя зовут?",
                "Je m'appelle .../Mon nom est ... --- Меня зовут .../Мое имя ...",
            ],
            "Прощание": [
                "Il est déjà tard. Je dois partir. --- Уже поздно. Мне пора идти.",
                "Je suis venu(е) pour vous dire au revoir. --- Я зашел/зашла попрощаться.",
                "Au revoir! --- До свидания!",
                "A bientôt. --- До скорой встречи.",
            ],
            "Благодарность. Извинение": [
                "Merci beaucoup. --- Большое спасибо.",
                "Je vous en prie. (обращение на «вы»)/Je t'en prie. (обращение на «ты») --- Пожалуйста.",
                "De rien./Pas de quoi. --- Не за что.",
                "Je suis désolé(e). Pardon./Excusez-moi. --- Мне очень жаль. Извините",
            ]
        },
        "Конструкции з глаголами être и avoir": [
            "être malade --- быть больным",
            "être bien --- быть здоровым",
            "être libre --- быть свободным",
            "être pris(e) --- быть занятым",
            "être prêt(e) --- быть готовым",
            "être marié(e) --- быть женатым (замужем)",
            "être en retard --- опаздывать",
            "être à l'heure --- приходить вовремя",
            "être fatigué(e) --- быть уставшим",
            "être désolé(e) --- сожалеть",
            "avoir peur --- de бояться",
            "avoir froid --- замерзнуть",
            "avoir besoin --- de нуждаться в чем-либо",
            "avoir raison --- быть правым",
            "avoir faim --- хотеть есть",
            "avoir soif --- хотеть пить",
            "avoir sommeil --- хотеть спать",
            "avoir lieu --- иметь место",
            "avoir de la chance --- быть удачливым",
            "avoir du succès --- иметь успех",
            "Je suis Russe. --- Я русский (-ая)",
            "J'ai 23 ans --- Мне 23 года",
            "Il est ingénieur --- Он инженер",
            "J'ai soif/faim --- Я хочу пить/есть",
            "Je suis fatigué --- Я устал",
            "Tu n'as pas raison --- Ты не прав(а)",
            "J'ai un frère --- У меня есть брат",
        ],
    },
    "Работа, профессии": {
        "Профессии": [
            "un juge --- судья",
            "une comptable --- бухгалтер",
            "un serveur --- официант",
            "un professeur --- учитель",
            "un pompier --- пожарный",
            "un matelot --- моряк",
            "un constructeur --- строитель",
            "un policier --- полицейский",
            "un conducteur --- водитель",
            "un cuisinier --- повар",
            "un clerk --- офис-менеджер",
            "un docteur --- врач",
            "une chanteuse --- певица",
            "un aviateur --- летчик",
            "un fermier --- фермер",
            "un facteur --- почтальон",
        ],
        "Составление резюме": {
            "Основные пункты резюме": [
                "information personnelle --- личные данные",
                "poste ou métier recherché --- должность, на которую претендует лицо",
                "formation --- образование",
                "stages --- стажировки",
                "expérience professionnelle --- профессиональный опыт",
                "date --- дата",
                "signature --- подпись",
            ],
            "Личностные характеристики": [
                "adaptable --- адаптирующийся",
                "méticuleux, -euse --- аккуратный",
                "analytique --- аналитик",
                "flexible --- гибкий",
                "discipliné, -e --- дисциплинированный",
                "sociable --- коммуникабельный",
                "sûr, -e --- надежный",
                "novateur, - trice --- новатор",
                "bien organisé, -e --- организованный",
                "responsable --- ответственный",
                "accommodant, -e --- покладистый ",
                "systématique --- последовательный",
                "pratique --- практичный",
                "fidèle --- преданный",
                "appliqué, -е --- прилежный",
                "ponctuel, -le --- пунктуальный",
                "créateur, -trice --- творческий",
                "travailleur, -euse --- трудолюбивый",
                "minutieux, -euse --- усердный",
                "honnête --- честный",
            ],
        },
        "Выбор профессии и прием на работу": [
            "Qu'est-ce que vous faites dans la vie?/Quelle est votre profession? --- Чем вы занимаетесь?/Какая у вас профессия?",
            "Je suis ingénieur/économiste/médecin/professeur. --- Я инженер/экономист/врач/преподаватель.",
            "travailler en qualité de/comme... --- работать в качестве…",
            "avoir une promotion --- получить повышение",
            "chercher un emploi --- искать работу",
            "trouver un emloi (un boulot) --- найти работу",
            "se mettre au travail --- приступить к работе",
            "s'embaucher, s'engager --- устраиваться на работу",
            "les inconvénients/les avantages du travail --- недостатки/преимущества в работе",
            "chercher un travail à mi-temps/pleinemploi/temporaire/permanent --- искать работу с неполным/полным рабочим днем/временную/постоянную",
            "travailler à deux postes --- работать в две смены",
            "travailler à domicile --- работать на дому",
            "faire des heures supplémentaires --- работать сверхурочно",
            "engager, embaucher --- нанимать кого-либо",
            "être au chômage --- быть безработным",
            "démissionner, licencier, virer, congédier --- уволить",
            "perdre le travail --- потерять работу",
            "prendre sa retraite --- пойти на пенсию",
            "quitter le service --- уйти в отставку",
            "être accro du boulot --- быть трудоголиком",
            "gagner bien sa vie --- хорошо зарабатывать",
            "le sphère des fonctions/des compétences --- круг обязанностей",
        ],
    },
    "Внешность": {
        "Части тела": [
            "une tête --- голова",
            "un front --- лоб",
            "une joue --- щека",
            "un visage --- лицо",
            "une poitrine --- грудь",
            "une taille --- талия",
            "un doigt --- палец (на руке)",
            "un genou --- колено",
            "un orteil --- палец (на ноге)",
            "une tempe --- висок",
            "un oeil --- глаз",
            "un nez --- нос",
            "un сou --- шея",
            "un dos --- спина",
            "une fesse --- ягодица",
            "une cheville --- щиколотка",
            "un talon --- пятка",
            "des cheveux --- волосы",
            "une épaule --- плечо",
            "un bras --- рука (от плеча до кисти)",
            "un coude --- локоть",
            "une main --- рука (кисть)",
            "une hanche --- бедро",
            "une jambe --- нога",
            "un pied --- ступня",
        ],
        "Описание внешности": {
            "_": [
                "Лицо --- Le visage",
                "Лоб --- Le front",
                "Нос --- Le nez",
                "Глаза --- Les yeux",
                "Губы --- Les lèvres",
                "Щеки --- Les joues",
                "Рот --- La bouche",
                "Кожа --- La peau",
                "Брови --- Les sourcils",
                "Ресницы --- Les cils",
                "Подбородок --- Le menton",
                "Фигура --- La taille",
                "Черты лица --- Les traits"
            ],
            "Лицо --- Le visage": [
                "pâle --- бледное",
                "beau --- красивое",
                "joli --- миленькое",
            ],
            "Лоб --- Le front": [
                "large / étroit --- широкий / узкий",
                "haut / bas --- высокий / низкий",
            ],
            "Нос --- Le nez": [
                "grand / petit --- большой / маленький",
                "long / court --- длинный / короткий",
                "droit / retroussé, camus --- прямой / курносый",
            ],
            "Глаза --- Les yeux": [
                "grands / petits --- большие / маленькие",
                "noirs / marron / gris / bleus --- черные / карие / серые / голубые",
                "en amande --- миндалевидные",
            ],
            "Губы --- Les lèvres": [
                "charnues / minces --- полные / тонкие",
                "roses --- розовые",
            ],
            "Щеки --- Les joues": [
                "rebondies / creuses --- пухлые / впалые",
                "pâles / vermeilles --- бледные / румяные",
                "pas rasées --- небритые",
            ],
            "Рот --- La bouche": [
                "ferme --- твердый",
                "bien dessinnée --- выразительный",
            ],
            "Кожа --- La peau": [
                "douce / dure --- нежная / грубая",
            ],
            "Брови --- Les sourcils": [
                "arqués --- дугой",
                "rectilignes --- прямые",
            ],
            "Ресницы --- Les cils": [
                "сourbés / droits --- загнутые / прямые",
                "épais --- густые",
            ],
            "Подбородок --- Le menton": [
                "pointu --- острый",
                "en galoche --- выдающийся",
            ],
            "Фигура --- La taille": [
                "grosse / mince --- полная / худощавая",
                "svelte --- изящная",
                "gracieuse --- грациозная",
            ],
            "Черты лица --- Les traits": [
                "prononcés --- крупные",
                "fins --- тонкие",
                "(ir)réguliers --- (не)правильные",
                "petits --- мелкие",
            ]
        },
        "Взгляд": [
            "atone --- безжизненный",
            "direct --- прямой",
            "fuyant --- блуждающий",
            "fâché --- сердитый",
            "rapide, vif --- быстрый",
            "sévère --- суровый",
            "furieux --- гневный",
            "passionné --- страстный",
            "doux --- добрый",
            "honteux --- стыдливый",
            "oblique --- косой",
            "atone, voilé --- тусклый",
            "morne --- мрачный",
            "fuyant --- уклоняющийся",
            "impatient --- нетерпеливый",
            "furtif, en coin, en coulisse --- украдкой",
            "absent, noyé --- отсутствующий",
            "éteint --- потухший",
            "suppliant --- умоляющий",
            "méprisant, dédaigneux --- презрительный",
            "froid --- холодный",
            "scrutateur, fixe --- пристальный",
            "espiègle --- шаловливый",
            "pénétrant, perçant --- пронизывающий",
            "acerbe --- язвительный",
        ],
        "Волосы и прическа": [
            "foncés --- темные",
            "teints --- крашеные",
            "châtains --- каштановые",
            "clairs --- светлые",
            "roux --- рыжие",
            "roussâtres --- рыжеватые",
            "noirs --- черные",
            "d'un blond doré --- золотистые",
            "blonds, clairs --- белокурые",
            "gris, blancs --- седые",
            "les cheveux --- волосы",
            "emmêlés --- растрепанные",
            "ébouriffés --- взъерошенные",
            "clairsemés --- редкие",
            "frisés --- волнистые",
            "mis en plis --- уложенные",
            "bouclés --- вьющиеся",
            "soyeux --- шелковистые",
            "épais, abondants --- густые",
            "chauve --- лысый",
            "longs --- длинные",
            "une coiffure --- прическа",
            "bouclés --- завитые",
            "une tresse --- коса",
            "ondulés --- завитые волнами",
            "une raie --- пробор",
            "tressés --- заплетенные",
            "une coupe --- стрижка",
            "courts --- короткие",
            "une mise en plis --- укладка",
            "crépus --- кудрявые",
            "la queue de cheval --- «хвост»",
            "lissеs --- приглаженные",
            "la barbe --- борода",
            "droits, plats --- прямые",
            "la calvitie --- лысина",
            "volumineux --- пышные",
            "la perruque --- парик",
            "tombants, décoiffés --- распущенные",
            "la moustache --- усы",
            "démêlés --- расчесанные",
            "un chignon --- шиньон",
        ],
        "Рука": [
            "la main --- рука (кисть)",
            "une paume --- ладонь",
            "le petit doigt --- мизинец",
            "un ongle --- ноготь",
            "l'annulaire --- безымянный палец",
            "le majeur/médius --- средний палец",
            "l'index --- указательный палец",
            "un doigt --- палец",
            "le pouce --- большой палец",
            "un muscle --- мышца",
            "la poignée --- запястье",
        ],
        "Эмоции": [
            "joyuex, -euse --- веселый",
            "pleurard, -e --- плаксивый",
            "émerveillé, -é --- восхищенный",
            "deprimé, -e --- подавленый",
            "triste; chagriné, -e --- грустный",
            "indifférent, -e --- равнодушный",
            "bon, -ne --- добрый",
            "radieux, -euse --- радостный",
            "amical, -e --- дружелюбный",
            "fâché, -e --- сердитый",
            "jovial, -e --- жизнерадостный",
            "rayonnant, -e --- сияющий",
            "méchant, -e --- злой",
            "heureux, -euse --- счастливый",
            "stupéfié, -e: ahuri, -e --- изумленный",
            "calme, tranquille --- спокойный",
            "sincère, candide --- искренний",
            "ouvert, -e --- открытый",
            "effaré, -e --- испуганный",
            "morose, maussade --- угрюмый",
            "comique --- комичный",
            "étonné, -e; surpris, -e --- удивленный",
            "malheureux, -euse --- несчастный",
            "souriant, -e --- улыбающийся",
            "affligé, -e --- печальный",
            "choqué, -e --- шокированный",
        ],
        "Сравнения для описания человека": [
            "Blanc comme le linge (la neige). --- Белый как полотно (снег).",
            "Pâle comme la mort. --- Бледный как смерть.",
            "Myope comme une taupe. --- Близорукий как крот.",
            "Rapide comme un éclair. --- Быстрый как молния.",
            "Savant comme un livre. --- Быть очень образованным.",
            "Libre comme l'air. --- Вольный как птица.",
            "Bête comme ses pieds. --- Глуп как пробка.",
            "Sourd comme un pot. --- Глухой как пень.",
            "Affamé comme un loup. --- Голодный как волк.",
            "Nu comme un ver. --- Голый как червь.",
            "Joli comme un cœur. --- Красивый как сердечко.",
            "Doux comme un agneau. --- Ласковый как ягненок.",
            "Léger comme une plume. --- Легкий как перышко.",
            "Muet comme une carpe. --- Нем как рыба.",
            "Haut comme trois pommes. --- От горшка два вершка.",
            "Fidèle comme un chien. --- Преданный как собака.",
            "Fort comme un bœuf. --- Сильный как бык.",
            "Dur comme le fer. --- Твердый как кремень.",
            "Sage comme une image. --- Тише воды, ниже травы.",
            "Laborieux comme une abeille. --- Трудолюбивый как пчела.",
            "Têtu comme une mule. --- Упрямый как осел.",
            "Brave comme un lion. --- Храбрый как лев.",
            "Maigre comme un clou. --- Худой как гвоздь.",
            "Propre comme un sou neuf. --- Чистый как новая монетка.",
        ],
    },
    "Жилье": {
        "Части дома": [
            "la cheminée --- дымоход",
            "le grenier --- чердак",
            "une mansarde --- мансарда",
            "un balcon --- балкон",
            "un étage --- этаж",
            "l'entrée --- вход",
            "la porche --- крыльцо",
            "un escalier --- лестница",
            "les fondations --- фундамент",
            "la fenêtre --- окно",
            "une clé --- ключ",
            "un châssis --- оконная рама",
            "la serrure --- замок",
            "la cave --- погреб",
            "la porte --- дверь",
            "le mur --- стена",
            "le toit --- крыша, кровля",
        ],
        "Дом и комнаты": [
            "la chambre à coucher --- спальня",
            "une nursery --- детская",
            "le salon/la salle à dîner --- общая комната, зал",
            "un garage --- гараж",
            "l'antichambre --- прихожая",
            "un garde-manger --- кладовая, чулан",
            "la buanderie --- прачечная",
            "la cuisine --- кухня",
            "la salle à manger --- столовая",
            "les toilettes --- туалет",
            "la salle de bains --- ванная",
            "le cabinet --- кабинет",
        ],
        "Мебель": [
            "une table basse --- журнальный стол",
            "un divan --- диван",
            "une chaise --- стул",
            "un fauteuil --- кресло",
            "un miroir --- зеркало",
            "une étagère --- полка",
            "un lit --- кровать",
            "un buffet --- буфет",
            "un placard --- платяной шкаф",
            "une commode --- комод",
            "une cheminée --- камин",
            "un meuble --- тумбочка",
            "une torchère --- торшер",
            "un lustre --- люстра",
            "un poste de télé --- телевизор",
            "un rideau --- штора",
        ],
        "Кухонные принадлежности": [
            "un pot --- кувшин",
            "une râpe --- терка",
            "une tasse et une soucoupe --- чашка с блюдцем",
            "un plat --- блюдо",
            "une fourchette --- вилка",
            "un couteau --- нож",
            "une cuillère à thé --- чайная ложка",
            "une cuillère --- ложка",
            "un verre --- стакан",
            "une louche --- половник",
            "une assiette --- тарелка",
            "un bol --- миска",
            "un bouilloir --- чайник",
            "une poêle (à frire) --- сковорода",
            "une passoire --- дуршлаг",
            "une planche --- доска",
        ],
        "Ванная и туалет": [
            "un lavabo --- умывальник",
            "une baignoire --- ванна",
            "une douche --- душ",
            "une cuvette --- унитаз",
            "le papier de toilette --- туалетная бумага",
            "le savon --- мыло",
            "une serviette --- полотенце",
            "un robinet --- кран",
            "la brosse à dents --- зубная щетка",
            "une pèse-personne --- напольные весы",
            "un peigne --- расческа",
            "un shampoing --- шампунь",
            "un gel nettoyant --- гель для душа",
            "la pâte dentifrice --- зубная паста",
            "une éponge --- мочалка",
            "une brosse --- щетка для волос",
        ],
        "Цвета": [
            "blanc, -he --- белый",
            "rouge --- красный",
            "jaune --- желтый",
            "bleu, -e --- синий, голубой",
            "gris, -e --- серый",
            "vert, -e --- зеленый",
            "violet, -te --- фиолетовый",
            "noir, -e --- черный",
            "brun, -e --- коричневый",
            "rose --- розовый",
            "orange --- оранжевый",
        ],
        "Формы": [
            "un carré --- квадрат",
            "un rectangle --- прямоугольник",
            "un hexagon --- шестиугольник",
            "un pentagon --- пятиугольник",
            "un cercle/rond --- круг",
            "un oval --- овал",
            "un triangle --- треугольник",
            "un losange --- ромб",
            "une étoile --- звезда",
            "le croissant --- полумесяц",
            "un coeur --- сердце",
        ],
    },
    "Рабочий день": {
        "Компьютер": [
            "le moniteur --- монитор",
            "un lecteur de disque --- дисковод",
            "l'unité centrale --- системный блок",
            "l'écran --- экран",
            "la clé USB --- флешка",
            "le clavier --- клавиатура",
            "une souris --- мышка",
            "un port --- разъем",
        ],
        "Рабочий кабинет": [
            "un bureau --- рабочий стол",
            "un portable --- ноутбук",
            "un fauteuil --- офисное кресло",
            "un stylo --- ручка",
            "une calculatrice --- калькулятор",
            "l'imprimante --- принтер",
            "une serviette --- портфель",
            "un horloge --- часы",
            "les livres --- книги",
            "un bloc-notes --- блокнот",
            "un agenda --- ежедневник",
            "une lampe --- настольная лампа",
            "un calendrier --- календарь",
            "un fichier --- папка",
            "un journal --- газета",
            "une pince --- скрепкa",
        ],
        "Назначение встречи": {
            "Просьба о встрече": [
                "Est-ce qu'on peut se voir cette semaine/demain? --- Мы можем встретиться на этой неделе/завтра?",
                "J'aimerais vous rencontrer cette semaine. C'est possible? --- Мне бы хотелось встретиться с вами на этой неделе. Это возможно?",
                "Vous êtes libre la semaine suivante? --- Свободны ли вы на следующей неделе?",
                "Ce vendredi vous convient? --- Пятница бы вас устроила?",
                "On peut se voir quand? --- Когда мы можем увидеться?",
                "Quand est-ce que vous êtes libre? --- Когда вы свободны?",
            ],
            "Ответ на назначение встречи": [
                "Я должен посмотреть свое расписание. --- Je dois consulter mon emploi de temps.",
                "Я смогу завтра. --- Je pourrai demain.",
                "Я еще не знаю, какие у меня планы на эту неделю. --- Je ne sais pas encore mon emploi de temps pour cette semaine.",
                "Меня это полностью устраивает. --- Ça me va parfaitement.",
            ],
            "Отмена встречи": [
                "Je suis désolé, mais je pars en mission cette semaine. --- Сожалею, но на этой неделе я уезжаю в командировку.",
                "Je suis très désolé(e), mais j'ai déjà un rendez-vous. --- Мне очень досадно, но у меня уже назначена встреча.",
                "Nous pourrions fixer un rendez-vous un autre jour? --- Мы можем назначить на другой день?",
            ],
            "Наиболее употребительные возвратные глаголы": [
                "s'amuser --- веселиться",
                "s'apercevoir --- замечать",
                "s'appeler --- называться",
                "s'approcher de --- приближаться",
                "s'arrêter --- останавливаться",
                "s'embrasser --- целоваться",
                "s'endormir --- засыпать",
                "s'ennuyer --- скучать",
                "s'entendre --- ладить друг с другом",
                "s'envoler --- взлетать",
                "s'essuyer --- вытираться",
                "s'exuser --- извиняться",
                "s'habiller --- одеваться",
                "s'habituer à --- привыкать",
                "s'installer --- устраиваться",
                "s'intéresser à --- интересоваться",
                "s'occuper de --- заниматься",
                "se couper --- порезаться",
                "se douter de --- сомневаться",
                "se fâcher contre --- сердиться",
                "se baigner --- купаться",
                "se coucher --- ложиться cпать",
                "se dépêcher --- торопиться",
                "se déshabiller --- раздеваться,",
                "se diriger --- направляться",
                "se lever --- вставать",
                "se marier --- жениться",
                "se mettre à --- приниматься за что-либо",
                "se nommer --- называться",
                "se peigner --- причесываться",
                "se perdre --- потеряться",
                "se préparer à --- готовиться",
                "se quitter --- расставаться",
                "se rappeler --- вспоминать",
                "se raser --- бриться",
                "se réveiller --- просыпаться",
                "se sentir --- чувствовать себя",
                "se souvenir --- вспомнить",
                "se taire --- замолкать",
                "se tromper --- ошибаться",
                "se trouver --- находиться",
                "se voir --- видеться",
            ],
        },
    },
    "Время, погода": {
        "_": [
            "L'hiver --- Зима",
            "Le printemps --- Весна",
            "L'été --- Лето",
            "L'autumne --- Осень",
            "Janvier --- январь",
            "Février --- февраль",
            "Mars --- март",
            "Avril --- апрель",
            "Mai --- май",
            "Juin --- июнь",
            "Juillet --- июль",
            "Août --- август",
            "Septembre --- сентябрь",
            "Octobre --- октябрь",
            "Novembre --- ноябрь",
            "Decembre --- декабрь",
            "en hiver --- зимой",
            "en été --- летом",
            "en automne --- осенью,",
            "au printemps --- весной",
        ],
        "Зима": [
            "neiger --- идти, падать (о снеге)",
            "faire froid --- холодать (о погоде), мороз",
            "luger --- кататься на санках",
            "patiner --- кататься на коньках",
            "des flocons de neige --- хлопья снега",
            "un cristal de neige --- снежинка",
            "une tempête du neige --- метель",
        ],
        "Весна": [
            "fondre --- таять (о снеге)",
            "pousser --- расти, произрастать",
            "verdir --- зеленеть",
            "fleirir --- цвести",
            "un bourgeon --- почка, бутон",
        ],
        "Лето": [
            "la chaleur --- жара",
            "se baigner --- купаться",
            "bronzer --- загорать",
            "nager --- купаться",
            "cueillir des baies --- собирать ягоды",
        ],
        "Осень": [
            "jaunir --- желтеть",
            "tomber --- падать",
            "faner --- увядать",
            "l'été indien --- бархатный сезон",
            "la boue --- грязь",
            "une flaque --- лужа",
            "le vent --- ветер",
            "la pluie --- дождь",
            "pleuvoir --- идти (о дожде)",
        ],
    },
    "Дни недели": [
        "lundi --- в понедельник",
        "mardi --- во вторник",
        "mercredi --- в среду",
        "jeudi --- в четверг",
        "vendredi --- в пятницу",
        "samedi --- в субботу",
        "dimanche --- в воскресенье",
        "le lundi --- по понедельникам",
        "le mardi --- по вторникам",
        "le mercredi --- по средам",
        "le jeudi --- по четвергам",
        "le vendredi --- по пятницам",
        "le samedi --- по субботам",
        "le dimanche --- по воскресеньям",
        "ce jeudi --- в этот четверг",
        "lundi passé --- в прошлый понедельник",
        "vers vendredi --- к пятнице",
        "demain --- завтра",
        "après-demain --- послезавтра",
        "hier --- вчера",
        "avant-hier --- позавчера",
        "un de ces jours --- на днях",
    ],
    "Время": [
        "il est une heure dix --- десять минут второго",
        "il est une heure et quart --- четверть второго",
        "il est une heure et demie --- половина второго",
        "il est deux heures moins vingt --- без двадцати два",
        "il est deux heures moins le quart --- без четверти два",
        "à minuit --- в полночь",
        "à midi --- в полдень",
        "il est environ deux heures --- около двух часов",
        "il est deux heures (précises) --- (ровно) два часа",
        "il est deux heures moins cinq --- без пяти два",
        "Quelle heure il est? --- Который час?",
        "Il est trois heures. --- Три часа.",
        "à/vers sept heures --- в/к 7:00",
        "la nuit --- ночью",
        "le matin --- утром",
        "le soir --- вечером",
        "dans la journée --- днем",
    ],
    "Погода": [
        "le soleil --- солнце",
        "un cristal de nеige --- снежинка",
        "une goutte --- капля",
        "un nuage --- туча",
        "le tonnerre --- гроза",
        "un arc-en-ciel --- радуга",
        "la pluie --- дождь",
        "la neige --- снег",
        "un ouragan --- ураган",
        "le vent --- ветер",
        "il fait chaud --- жарко",
        "il fait froid --- холодно",
        "un brouillard --- туман",
        "la nébulosité --- облачность",
        "un éclair --- молния",
        "ensoleillé, -e --- солнечный, -ая",
    ],
    "Безличные глаголы": {
        "Явления природы": [
            "il pleut --- идет дождь",
            "il bruine --- моросит",
            "il grésille --- сыпет мелкая крупа",
            "il neige --- идет дождь",
            "il grêle --- идет град",
            "il dégèle --- теплеет, наступает оттепель,",
            "il vente --- дует ветер",
            "il fait beau --- тепло, стоит хорошая погода",
            "il fait mauvais --- погода плохая",
            "il fait froid --- холодно",
            "il fait frais --- свежо",
            "il fait humide --- сыро",
            "il fait du vent --- ветрено",
            "il fait du brouillard --- туманно",
            "il fait du verglas --- гололедица",
            "il fait de la pluie --- идет дождь",
        ],
        "Время": [
            "il est midi --- полдень",
            "il est minuit --- полночь",
            "il est deux heures et demie --- половина третьего",
            "il est le 1er janvier --- первое января",
            "il fait nuit --- темно (ночь)",
            "il fait jour --- светло (день)",
        ],
        "Существование": [
            "il est --- есть",
            "il existe --- существует",
            "il y a --- имеется",
        ],
        "Суждение": [
            "il faut --- нужно",
            "il se peut --- случается",
            "il est possible --- возможно",
            "il est certain --- точно",
            "il est utile --- полезно",
            "il est bon --- хорошо",
            "il est difficile --- трудно",
            "il est agréable --- приятно",
            "il est nécessaire --- необходимо",
        ],
    },
    "Порядковые числительные": [
        "1 un --- premier, -ère",
        "2 deux --- deuxième",
        "3 trois --- troisième",
        "4 quatre --- quatrième",
        "5 cinq --- cinquième",
        "6 six --- sixième",
        "7 sept --- septième",
        "8 huit --- huitième",
        "9 neuf --- neuvième",
        "10 dix --- dixième",
        "11 onze --- onzième",
        "12 douze --- douzième",
        "13 treize --- treizième",
        "14 quatorze --- quatorzième",
        "15 quinze --- quinzième",
        "16 seize --- seizième",
        "17 dix-sept --- dix-septième",
        "18 dix-huit --- dix-huitième",
        "19 dix-neuf --- dix-neuvième",
        "20 vingt --- vingtième",
        "21 vingt-et-un --- vingt-et-unième",
        "30 trente --- trentième",
        "40 quarante --- quarantième",
        "50 cinquante --- cinquantième",
        "60 soixante --- soixantième",
        "70 soixante-dix --- soixante-dixième",
        "80 quatre-vingt --- quatre-vingtième",
        "90 quatre-vingt-dix --- quatre-vingt-dixième",
        "100 cent --- centième",
        "1000 mille --- millième",
    ],
    "Путешествие": {
        "Вокзал": [
            "un train --- поезд",
            "une voiture --- вагон",
            "la gare --- вокзал",
            "la consigne --- камера хранения",
            "une étiquette --- багажный ярлык",
            "un billet --- билет",
            "l'indicateur/un panneau --- указатель пункта назначения",
            "un quai --- платформа",
            "le chemin de fer --- железная дорога",
            "le porteur --- носильщик",
            "la salle d'attente --- зал ожидания",
            "une valise --- чемодан",
            "une poubelle --- урна для мусора",
            "un horloge --- часы",
            "une voiturerestaurant --- вагон-ресторан",
            "un passeport --- паспорт",
        ],
        "Виды транспорта": [
            "un hélicoptère --- вертолет",
            "un motocycle --- мотоцикл",
            "un avion --- самолет",
            "un bus/un car --- автобус",
            "un bateau --- лодка",
            "un trolleybus --- троллейбус",
            "un navire --- корабль",
            "un yacht --- яхта",
            "une bicyclette --- велосипед",
            "le métro --- метро",
            "une voiture --- машина",
            "un tram --- трамвай",
            "un camion --- грузовик",
            "un taxi --- такси",
            "un liner --- лайнер",
            "un funiculaire --- фуникулер",
        ],
        "На вокзале: полезные фразы": {
            "_": [
                "Багаж --- Les bagages",
                "На вокзале --- À la gare",
                "В вагоне --- Dans une voiture",
            ],
            "Багаж": [
                "Où est la consigne? --- Где находится камера хранения?",
                "Je voudrais récupérer mes bagages. --- Я хочу забрать свой багаж.",
            ],
            "На вокзале": [
                "Où est la caisse --- Где билетная касса",
                "la salle d'attente --- — зал ожидания",
                "— un restaurant --- — ресторан",
                "— la sortie aux quais --- — выход к платформам",
                "— l'horaire des trains --- — расписание поездов",
                "— le bureau de renseignements? --- — справочное бюро?",
                "Quand commence l'embarquement? --- Когда начинается посадка?",
                "Combien coûte un billet (un aller-retour) à …? --- Сколько стоит билет до ... (и назад)?",
                "J'ai besoin d'un billet à ... --- Мне нужен один билет до ...",
                "Est-ce qu'il faut faire une correspondance? --- Нужно ли мне делать пересадку?",
                "Quelle est ma voiture? --- Какой номер моего вагона?",
                "L'accès au quai numéro 2, s'il vous plaît? --- Как пройти на вторую платформу?",
                "A quel quai arrive le train? --- На какую платформу (путь) прибывает поезд?",
            ],
            "В вагоне": [
                "C'est mon compartiment. --- Это мое купе.",
                "J'ai une couchette de bas (de haut). --- У меня нижнее (верхнее) место.",
                "Puis-je allumer (éteindre) l'électricité? --- Можно включить (выключить) свет?",
                "Combien de minutes le train s'arrête ici? --- Сколько минут стоит тут поезд?",
                "Quelle est la station suivante? --- Какая следующая остановка?",
            ],
        },
        "В аэропорту и самолете: полезные фразы": [
            "Où peut-on acheter le billet pour l'avion? --- Где можно купить билет на самолет?",
            "A quelle heure part (arrive) l'avion? --- Когда вылетает (прибывает) самолет?",
            "Je veux confirmer mon vol. --- Я хочу подтвердить мой рейс.",
            "A quelle heure est mon vol? --- В котором часу мой рейс?",
            "А quelle heure part le vol pour ...? --- В котором часу рейс на …?",
            "Est-ce un vol direct? --- Это прямой рейс (без пересадок)?",
            "Avez-vous des places pour le vol numéro … à destination de …? --- Есть ли у вас места на рейс N … до …?",
            "Je suis arrivé en retard pour l'avion numéro … --- Я опоздал на самолет, который следует рейсом N …",
            "Combien de temps dure le vol de … à destination de …? --- Сколько времени продолжается полет из … на …?",
            "Je voudrais une place à coté du hublot, s'il vous plaît. --- Я бы хотел(а) место возле иллюминатора, пожалуйста.",
            "Je voudrais un aller-simple/un aller-retour pour ... --- Я бы хотел(а) билет туда-обратно/в одну сторону до …",
            "Où a lieu l'enregistrement du bagage? --- Где проходит регистрация багажа?",
            "Vers quelle porte faut-il aller pour l'embarquement? --- К какому выходу пройти на посадку?",
            "Je peux voir votre passeport? --- Можно ваш паспорт?",
            "Je n'ai rien à déclarer. --- Мне нечего декларировать.",
            "Combien de bagages je peux prendre avec moi? --- Сколько багажа можно взять с собой?",
            "Je dois peser mon bagage. --- Мне нужно взвесить багаж.",
            "On a déjà annoncé le vol? --- Объявили ли, когда вылетает рейс?",
            "Combien d'heures dure le vol? --- Сколько часов продолжается полет?",
        ],
        "Части машины": [
            "le capot --- капот",
            "une aile avant --- переднее крыло",
            "une portière --- дверца",
            "une roue --- автомобильное колесо",
            "un siège --- сиденье",
            "la planche de bord --- приборная панель",
            "un rétroviseur --- зеркало заднего вида",
            "un essuie-glace --- стеклоочиститель",
            "un phare --- фара",
            "une batterie --- аккумулятор",
            "le levier de vitesse --- рычаг переключения скоростей",
            "un volant --- руль",
            "le coffre --- багажник",
            "un moteur --- двигатель",
            "la clé de contact --- ключ зажигания",
            "un pneu --- шина (покрышка)",
        ],
    },
    "Город": {
        "В городе": [
            "une rue --- улица",
            "un bâtiment --- здание",
            "la route --- дорога",
            "un feu vert --- светофор",
            "la station-service --- АЗС",
            "la station de taxis --- стоянка такси",
            "un magasin --- магазин",
            "un hôtel --- отель",
            "une pharmacie --- аптека",
            "une usine --- завод",
            "un musée --- музей",
            "un restaurant --- ресторан",
            "un signal routier --- дорожный знак",
            "un carrefour --- перекресток",
            "un passage piéton --- переход «зебра»",
            "un parking --- стоянка",
        ],
        "Части города": [
            "un boulevard --- бульвар",
            "un arrondissement --- департамент",
            "un site ou un monument historique --- достопримечательность",
            "un quartier --- квартал",
            "un quai --- набережная",
            "une périphérie --- окраина",
            "les alentours, les environs --- окрестности",
            "un district [-k(t)] --- округ",
            "le périphérique --- окружная дорога",
            "une ruelle, une petite rue --- переулок",
            "une place --- площадь",
            "un faubourg, une banlieue --- предместье",
            "une avenue --- проспект",
            "une région, un district [-k(t)], un arrondissement --- район",
            "une impasse, un cul-de-sac --- тупик",
            "un coin --- угол",
            "une rue --- улица",
            "le centre --- центр",
            "un centre-ville --- центр города",
        ],
        "Направления движения": [
            "à droite / à gauche --- направо / налево; справа/слева",
            "tout droit --- прямо",
            "en haut/en bas de la rue --- вверх / вниз по улице",
            "derrière le coin --- за углом",
            "au coin --- на углу",
            "le long de --- вдоль",
            "par, à travers --- через",
            "près de, à côté de --- рядом",
            "en arrière / en avant --- назад / вперед",
            "en face de --- напротив",
            "devant --- мимо",
            "par là, de ce côté --- в эту сторону",
        ],
        "В поисках правильного направления": [
            "Je suis étranger(-ère) et je ne connais pas la ville. --- Я иностранец/иностранка и не знаю города.",
            "Je me suis égaré(e). --- Я заблудился(-лась).",
            "Où est …, s'il vous plaît? --- Скажите, пожалуйста, где находится …?",
            "Je cherche …, s'il vous plaît. --- Я ищу …",
            "Comment s'appelle cette rue /cette place? --- Как называется эта улица / площадь?",
            "Où se trouve la station du métro la plus proche/le commissariat/le consulat de la Russie? --- Где находится ближайшая станция метро / полицейский участок / консульство России?",
            "Comment aller au centre-ville, s'il vous plaît? --- Как добраться до центра города?",
            "Combien de temps ça prend pour y aller? --- Сколько времени нужно, чтобы добраться туда?",
            "Cela prendra près de 5 minutes. --- Это займет около 5 минут.",
            "Vous savez où c'est? --- Вы знаете, где это находится?",
            "Suivez ce chemin. --- Идите дальше по этой дороге.",
            "Traversez la rue. --- Перейдите улицу.",
            "Le deuxième tournant à droite. --- Второй поворот направо.",
            "C'est par là. --- Это туда.",
            "Je peux y aller à pied? --- Я могу дойти туда пешком?",
            "Je peux y aller par bus? --- Можно ли доехать автобусом?",
            "C'est à gauche ou à droite? --- Это слева или справа?",
            "Où dois-je tourner? --- Где мне повернуть?",
            "Tournez le coin. --- Поверните за угол.",
            "Pourriez-vous le montrer sur le plan? --- Вы не могли бы показать мне это на карте?",
        ],
    },
    "Гостиница, кемпинг": {
        "В гостиничном номере": [
            "un hôtel --- гостиница",
            "un portier --- портье",
            "une clé électronique --- электронный ключ",
            "la réception --- стойка портье",
            "le numéro de la chambre --- номер комнаты",
            "ne pas déranger --- не беспокоить",
            "l'Internet --- Интернет",
            "un coffre-fort --- сейф",
            "le lit --- кровать",
            "le service --- обслуживание",
            "les bagages --- багаж",
            "un café --- кафе",
            "la réservation --- бронь",
            "la salle de bains --- ванная комната",
            "les WC --- туалет",
            "un mini-bar --- мини-бар",
        ],
        "В гостинице: полезные фразы": [
            "Je voudrais réserver une chambre simple/double. --- Я хотел бы забронировать номер на одного человека/на двух человек.",
            "Avez-vous des сhambres libres? --- У вас есть свободные номера?",
            "Pour combien de personnes? --- На сколько человек?",
            "Combien coûte une chambre pour deux personnes par jour? --- Сколько стоит двухместный номер за сутки?",
            "Combien coûte une chambre pour 24 heures (avec le petit déjeuner)? --- Сколько стоит номер в сутки (с завтраком)?",
            "Je voudrais une chambre avec salle de bain/balcon. --- Я бы хотел(а) номер с ванной комнатой/балконом.",
            "Je voudrais une chambre qui donne sur la rue. --- Я хочу номер, который выходит на улицу.",
            "J'ai besoin d'une chambre avec un climatiseur. --- Мне нужен номер с кондиционером.",
            "Nous avons besoin d'une chambre avec/sans baignoire. --- Нам нужен одноместный номер с ванной/без ванны.",
            "Cette chambre (ne) me plaît (pas). --- Этот номер мне (не) нравится.",
            "Cette chambre me convient/ne me convient pas. --- Этот номер мне подходит/не подходит.",
            "Pouvez-vous monter mes bagages dans la chambre? --- Вы можете поднять мой багаж в номер?",
            "Quand partez-vous? --- Когда вы уезжаете?",
            "Je pars après-demain à six heures du matin. --- Я уезжаю послезавтра в 6 часов утра.",
            "Je ne sais pas encore combien de temps je vais rester. --- Я еще не знаю, сколько времени я у вас останусь.",
            "Préparez, s'il vous plaît, la note. --- Приготовьте, пожалуйста, счет.",
            "Pouvez-vous m'appeler un taxi? --- Вы можете мне вызвать такси?",
        ],
        "Отдых на природе": [
            "une caravane --- фургон, трейлер",
            "une jumelle --- бинокль",
            "une tente --- палатка",
            "un feu --- костер",
            "la lampe de poche --- фонарик",
            "du bois --- дрова",
            "des conserves --- консервы",
            "le sac de couchage --- спальный мешок",
            "un sac à dos --- рюкзак",
            "une chaise longue --- шезлонг",
            "un parasol --- зонт от солнца",
            "une boussole --- компас",
            "une hache --- топор",
            "la forêt/le bois --- лес",
            "la ligne à pêche --- удочка",
            "un seau --- ведро",
        ],
        "Отдых в кемпинге: полезные фразы": [
            "Puis-je camper ici? --- Могу я здесь расположиться лагерем?",
            "Est-ce que lе camping est autorisé ici? --- Здесь разрешен кемпинг?",
            "Oui, c'est un endroit convenable. --- Да, это подходящее место для кемпинга.",
            "Oui, vous pouver camper ici sans problème. --- Да, вы можете здесь расположиться лагерем без проблем.",
            "Pouvons-nous garer notre caravane ici? --- Можем ли мы припарковать наш трейлер здесь?",
            "Où se trouve le tеrrain de camping/caravaning le plus proche? --- Где находится ближайшая площадка для кемпинга?",
            "Quel est le prix pour une nuit? --- Какая цена за одну ночь?",
            "Le prix est ... euros. --- Цена … евро.",
            "Comment ce terrain est équipé? --- Как оснащена эта площадка?",
            "Ici il y a tout le nécessaire pour le confort des campeurs. --- Здесь есть всe необходимое для комфорта отдыхающих.",
            "Est-ce que je pеux faire un feu ici? --- Я могу здесь разводить костeр?",
            "Oui, mais il faut être très prudent. --- Да, но нужно быть очень аккуратным.",
            "Y a-t-il de l'eau potable ici? --- Здесь есть питьевая вода?",
            "Oui, il y en a, elle est dans les barriques grises là-bas. --- Да, есть, она находится в серых бочках вон там.",
            "Savez-vous où je peux trouver ...? --- Знаете ли вы, где я могу найти …?",
            "Vous devez vous adresser au gérant. --- Вам нужно обратиться к управляющему.",
            "Ce service est gratuit? --- Эта услуга предоставляется бесплатно?",
            "Non, vous devez payer un supplément. --- Нет, вам нужно доплатить.",
            "Est-ce qu'il y a ici Wi-Fi gratuit? --- Здесь есть бесплатный Wi-Fi?",
        ],
    },
    "Досуг, хобби, предпочтения": {
        "Глаголы aimer, adorer, détester, (dé)plaire": [
            "plaire --- нравиться",
            "adorer --- обожать",
            "aimer --- любить, нравиться",
            "aimer mieux --- предпочитать",
            "je voudrais --- я бы хотел",
            "préférer --- предпочитать",
            "détester --- ненавидеть",
            "déplaire --- не нравиться",
        ],
        "Виды досуга": [
            "le sport --- спорт",
            "une randonnée --- поход",
            "un voyage --- путешествие",
            "des jeux vidéo --- видеоигры",
            "la chasse --- охота",
            "la pêche --- рыбалка",
            "le jardinage --- садоводство",
            "la photographie --- фотографирование",
            "le dessin --- рисование",
            "les échecs --- шахматы",
            "le tricotage --- вязание спицами",
            "le crochetage --- вязание крючком",
            "la couture --- шитье",
            "la lecture --- чтение",
            "une visite au musée / au cinéma / au théâtre / au cirque / à la discothèque --- поход в музей / кино / театр / цирк / на дискотеку",
            "le bronzage --- загорание на пляже",
            "faire du sport --- заниматься спортом",
            "randonner --- идти в поход",
            "voyager --- путешествовать",
            "jouer aux jeux vidéo --- играть в видеоигры",
            "chasser --- охотиться",
            "pêcher --- рыбачить",
            "planter, jardiner --- сажать",
            "prendre des photos --- фотографировать",
            "dessiner --- рисовать",
            "jouer aux échecs --- играть в шахматы",
            "tricoter --- вязать спицами",
            "crocheter --- вязать крючком",
            "coudre --- шить",
            "lire --- читать",
            "aller au musée / au cinéma / au théâtre / au cirque / à la discothèque --- ходить в музей / кино /театр / цирк / на дискотеку",
            "bronzer --- загорать",
        ],
        "Досуг, хобби, предпочтения": [
            "le badminton --- бадминтон",
            "le basketball --- баскетбол",
            "le rugby --- регби",
            "la natation --- плавание",
            "le baseball --- бейсбол",
            "le bowling --- боулинг",
            "le tennis de table --- настольный теннис",
            "le football --- футбол",
            "la plongée sousmarine --- дайвинг",
            "le hockey --- хоккей",
            "le golf --- гольф",
            "la boxe --- бокс",
            "le volleyball --- волейбол",
            "le cyclisme --- велосипедный спорт",
            "le skating --- катание на скейтборде",
            "le billiard --- бильярд",
        ],
        "Искусство": [
            "une sculpture --- скульптура",
            "un tableau --- картина",
            "le cadre --- рама",
            "les peintures --- краски",
            "un chevalet --- мольберт",
            "un chef-d'oeuvre --- шедевр",
            "le théâtre --- театр",
            "le cinéma --- кино",
            "l'architecture --- архитектура",
            "la photographie --- фотография",
            "la musique --- музыка",
            "le ballet --- балет",
            "le livre --- книга",
            "un vitrail/une verrière --- витраж",
            "une icône --- икона",
            "la littérature --- литература",
        ],
    },
    "Шопинг": {
        "Отделы в универмаге": [
            "Parapharmacie --- Аптечная косметика",
            "Lingerie --- Белье",
            "Mercerie --- Галантерея",
            "Jouets --- Детские игрушки",
            "Papeterie --- Канцелярия",
            "Produits de beauté --- Косметика",
            "Chaussures --- Oбувной отдел",
            "Vêtements --- Одежда",
            "Vêtements femmes --- Одежда женская",
            "Vêtements hommes --- Одежда мужская",
            "Vêtements enfants --- Одежда для детей",
            "Parfumerie --- Парфюмерия",
            "Vaisselles --- Посуда",
            "Matériaux --- Строительные материалы",
            "Tissus --- Ткани",
            "Fleurs --- Цветочный отдел",
            "Produits élecroménagers --- Электротовары",
            "Bijouterie --- Ювелирный отдел",
        ],
        "Продовольственные отделы": [
            "Epicerie --- Бакалея",
            "Boulangerie --- Булочная",
            "Charcuterie --- Колбасный отдел",
            "Pâtisserie/Confiserie --- Кондитерская",
            "Conserves --- Консервы",
            "Pâtes --- Макароны",
            "Literie --- Молочные продукты",
            "Fruits de mer --- Морепродукты",
            "Boucherie --- Мясной отдел",
            "Boissons --- Напитки",
            "Légumes --- Овощи",
            "Vainde fraîche --- Свежее мясо",
            "Epices --- Специи",
            "Fromages --- Сыры",
            "Fruits --- Фрукты",
            "Poissonerie --- Рыба",
        ],
        "Обувь и кожгалантерея": [
            "les bottes --- сапоги",
            "les claquettes/tongs --- сланцы",
            "les mules --- туфли без задника",
            "la ceinture --- ремень",
            "les bottines --- ботинки",
            "les souliers --- мужские туфли",
            "les bottes de caouthcouc --- резиновые сапоги",
            "un sac à main --- сумка",
            "les pantoufles --- тапочки",
            "les souliers à talon --- туфли на высоком каблуке",
            "les chaussons --- туфли",
            "une serviette --- портфель",
            "les baskets --- кроссовки",
            "les ballerines --- балетки",
            "les nu-pieds --- босоножки",
            "une valise --- чемодан",
        ],
        "Одежда": [
            "une robe --- платье",
            "un tailleur --- костюм женский",
            "un T-shirt --- футболка",
            "un chemisier --- блуза",
            "un pull-over --- пуловер",
            "une veste --- пиджак",
            "une chemise --- рубашка",
            "un maillot de bains --- купальник",
            "un pantalon --- брюки",
            "une parka --- куртка",
            "un manteau --- пальто",
            "une culotte --- трусики",
            "une jupe --- юбка",
            "un jeans --- джинсы",
            "un short --- шорты",
            "un soutien-gorge --- бюстгальтер",
        ],
        "Аксессуары и головные уборы": [
            "un chapeau --- шляпа",
            "les bas --- чулки",
            "une écharpe --- шарф",
            "les boucles d'oreilles --- серьги",
            "les gants --- перчатки",
            "le collant --- колготки",
            "les lunettes --- очки",
            "une casquette --- кепка",
            "une cravate --- галстук",
            "une bague --- кольцо",
            "un parapluie --- зонт",
            "un papillon --- бабочка",
            "un foulard --- платок/косынка",
            "un bracelet --- браслет",
            "un collier --- колье",
            "les mouffles --- варежки",
        ],
        "Шопинг: полезные фразы": [
            "— Могу ли я вам помочь? — Нет, спасибо. Я просто смотрю. --- — Je peux vous aider? — Non, merci. Je ne fais que regarder.",
            "Я хотел бы купить свитер / пиджак / пару туфель / пару джинсов. --- Je voudrais acheter un pull-over /une veste / une paire de souliers /un jeans.",
            "Извините, не могли бы вы мне помочь? --- Excusez-moi, pourriez-vous m'aider?",
            "Я ищу серый костюм. --- Je cherche un costume gris.",
            "Какого размера одежду вы носите? --- Vous portez quelle taille?",
            "Могу я это примерить? --- Je peux l'essayer?",
            "Где это было сделано? --- C'est fabriqué où?",
            "Мне нужна шляпа к этому платью. --- J'ai besoin d'un chapeau pour cette robe.",
            "Я хотел бы то же самое другого цвета. --- Je voudrais la même chose mais d'une autre couleur.",
            "Туфли очень удобные. --- Les chaussures sont très commodes.",
            "Эти туфли мне жмут. --- Ces chaussures me serrent.",
            "Сколько это стоит? Я это возьму. --- Combien ça coûte? Je le prends.",
            "Не могли бы вы показать мне что-то менее дорогое? --- Pourriez-vous me montrer quelque chose de moins cher?",
            "Я оплачу кредитной карточкой. --- Je vais payer par carte.",
            "Я заплачу наличными. --- Je vais payer en liquide.",
            "Дайте мне квитанцию, пожалуйста. --- Donnez-moi, un reçu, s'il vous plaît.",
            "Вы работаете с доставкой? --- Vous faites la livraison?",
            "Я хотел бы заменить это, пожалуйста. --- Je voudrais remplacer cela, s'il vous plaît.",
            "Я хотел бы вернуть это, пожалуйста. --- Je voudrais retourner cela, s'il vous plaît.",
            "Я хотел бы получить деньги назад. --- Je voudrais que vous me remboursiez.",
        ],
        "Косметика и аксессуары": [
            "un rouge à lèvres --- помада",
            "les ombres à paupières --- тени для век",
            "une houppe --- кисть для пудры",
            "un vernis à ongles --- лак для ногтей",
            "un parfum --- духи",
            "la poudre --- пудра",
            "une trousse --- косметичка",
            "un déodorant --- дезодорант",
            "une crème --- крем",
            "un mascara --- тушь",
            "un crayon --- карандаш",
            "les ciseaux --- ножницы",
            "l'ombre à joues --- румяна",
            "une brosse --- расческа",
            "une lime --- пилочка для ногтей",
            "la crème aprèsrasage --- крем после бритья",
        ],
        "Деньги": [
            "un distributeur --- банкомат",
            "une banque --- банк",
            "un bureau de change --- пункт обмена валют",
            "un coffre-fort --- сейф",
            "la devise --- валюта",
            "une carte de crédit --- кредитная карта",
            "la caisse --- касса в магазине",
            "une coupure --- купюра",
            "une calculatrice --- калькулятор",
            "un virement --- денежный перевод",
            "des lingots --- слитки",
            "les monnaies --- монеты",
            "une tirelire --- копилка",
            "un porte-monnaie --- кошелек",
            "l'argent --- деньги",
            "la richesse --- богатство",
        ],
    },
    "О еде": {
        "Овощи и фрукты": [
            "des pommes de terre --- картофель",
            "le choux --- капуста",
            "les fraises --- клубника",
            "une pastèque --- арбуз",
            "la сarrote --- морковь",
            "le maЇs --- кукуруза",
            "un abricot --- абрикос",
            "une pomme --- яблоко",
            "une tomate --- помидор",
            "un citron --- лимон",
            "une cerise --- вишня",
            "une poire --- груша",
            "un concombre --- огурец",
            "une prune --- слива",
            "le raisin --- виноград",
            "un poivron --- сладкий перец",
        ],
        "Специи и травы": [
            "un oignon --- лук",
            "un aneth --- укроп",
            "un piment --- жгучий перец",
            "un cinnamome --- корица",
            "un ail --- чеснок",
            "la menthe --- мята",
            "un thym --- чабрец",
            "la roquette --- руккола",
            "un gingembre --- имбирь",
            "le poivre --- перец-горошек",
            "le laurier --- лавровый лист",
            "une oseille --- щавель",
            "le persil --- петрушка",
            "le clou de girofle --- гвоздика",
            "la mélisse --- мелисса",
            "la lavande --- лаванда",
        ],
        "Еда и напитки": [
            "le poulet --- курица",
            "le fromage --- сыр",
            "un sandwich --- бутерброд",
            "le pain --- хлеб",
            "le thé --- чай",
            "un gâteau --- пирожное",
            "les noix --- орехи",
            "la glace --- мороженное",
            "la viande --- мясо",
            "le poisson --- рыба",
            "les oeufs --- яйца",
            "le miel --- мед",
            "le vin --- вино",
            "le jus --- сок",
            "le lait --- молоко",
            "l'eau --- вода",
        ],
        "Характеристика пищевых продуктов по вкусу": [
            "appétissant, -e --- аппетитный",
            "bon, -ne; délicieux, -euse --- вкусный",
            "amer, -ère --- горький",
            "gras, -se --- жирный",
            "fort, -e --- крепкий (о чае, кофе)",
            "doux, douce --- мягкий",
            "mauvais, -e; mal cuisiné, -e --- невкусный",
            "pas assez salé, -e --- недосоленный",
            "fort, -e; piquant, -e --- острый",
            "savoureux, -euse --- очень вкусный",
            "trop salé, -e --- пересоленный",
            "maigre --- постный",
            "insipide --- пресный (о вкусе)",
            "aigre, tourné, -e --- прокисший",
            "sucré, -e --- сладкий",
            "salé, -e --- соленый",
            "sec, sèche --- сухой",
            "croustillant, -e --- хрустящий",
        ],
        "По степени готовности, возможности употребления": [
            "surgelé, -e; congelé, -e --- замороженный",
            "non-potable --- не питьевой",
            "mal cuit, -e --- недожаренный",
            "immangeable; non comestible --- несъедобный",
            "refroidi, -e --- охлажденный",
            "trop cuit, -e --- пережаренный",
            "potable --- питьевой",
            "saigné, -e --- с кровью (о мясе)",
            "frais, fraîche --- свежий",
            "mûr, -e --- спелый",
            "mangeable; comestible --- съедобный",
            "mal cuit, -e; cru, -e --- сырой",
            "bien cuisiné, -e --- хорошо приготовленный",
            "rassis, -e --- черствый",
        ],
        "На рынке: полезные фразы": [
            "Où on vend de la viande? --- Где продают мясо?",
            "Combien vous voulez pour ça? --- Сколько вы за это просите?",
            "Combien ça va faire en tout? --- Сколько все это будет стоить?",
            "Pesez ça, s'il vous plaît. --- Взвесьте, пожалуйста.",
            "Versez un litre, s'il vous plaît. --- Налейте, пожалуйста, литр.",
            "Montrez-moi un (une) autre, s'il vous plaît. --- Покажите мне, пожалуйста, другое.",
            "Montrez-moi, un autre morceau sans os. --- Покажите мне, пожалуйста, кусочек без костей.",
            "Je n'aime pas ce morceau. Donnez-moi celui-ci. --- Мне не нравится этот кусок. Покажите мне тот.",
            "J'ai besoin d'un morceau pour le cuire (frire, rôtir). --- Мне нужен кусочек, чтобы варить (жарить, тушить).",
            "J'ai peur que ce brochet n'est pas trop frais. --- Боюсь, что эта щука не совсем свежая.",
            "Je voudrais des œufs frais, s'il vous plaît. --- Мне бы хотелось свежих яиц.",
            "C'est de la crème fraîche? --- У вас сметана?",
            "Est-ce que je peux commander le même fromage pour la prochaine fois? --- Мог(ла) бы я заказать у вас тот же вид сыра на следующий раз?",
            "Si j'achète en gros, ça va être meilleur marché? --- Если я куплю оптом, будет ли это дешевле?",
            "Vous pourriez l'envelopper? --- Можно это запаковать?",
            "Nous pouvons marchander? --- Мы можем договориться о цене?",
        ],
        "В ресторане": [
            "un serveur --- официант",
            "une table --- столик",
            "un chandelier --- подсвечник",
            "une bougie --- свеча",
            "les visiteurs --- посетители",
            "une chaise --- стул",
            "la vaisselle --- посуда",
            "un verre de vin --- бокал",
            "une serviette --- салфетка",
            "une nappe --- скатерть",
        ],
    },
    "В ресторане: полезные фразы": {
        "_": [
            Бронь столика La résérvation de la table
            Заказ La commande
        ],
        "Бронь столика": [
            "Je peux vous aider? --- Чем я могу вам помочь?",
            "Je voudrais résérver une table pour le dîner. --- Я бы хотел заказать столик на обед.",
            "Je voudrais une table pour deux personnes. --- Я бы хотел столик на двоих.",
            "Nous voudrions prendre place dans un coin/près de la fenêtre. --- Мы бы хотели сесть в углу/у окна.",
            "Vous venez à quelle heure? --- В котором часу вы придете?",
        ],
        "Заказ": [
            "La carte, s'il vous plaît? --- Можно меню, пожалуйста.",
            "Avez-vous déjà choisi? --- Вы уже выбрали?",
            "Qu'allez-vous recommander? --- Что вы нам посоветуете?",
            "Quel est le plat du jour aujourd'hui? --- Какое сегодня дежурное блюдо?",
            "Quelle est votre spécialité de la maison? --- Какое у вас фирменное блюдо?",
            "Quelque chose de léger, s'il vous plaît. --- Что-нибудь легкое, пожалуйста.",
            "Qu'est-ce que vous voudriez boire? --- Что бы вы хотели выпить?",
            "Nous pouvons annuler la commande? --- Мы можем отменить заказ?",
            "Nous voudrions commander quelque chose de la cuisine française. --- Мы хотели бы заказать что-нибудь из французской кухни.",
            "Pourriez-vous apporter la carte des vins? --- Не могли бы вы принести нам карту вин?",
            "Je voudrais de la glace pour le dessert. --- Я бы хотел(а) на десерт мороженое.",
            "Un café/un thé seulement. --- Один кофе/чай, пожалуйста.",
            "L'addition, s'il vous plaît. --- Принесите счет, пожалуйста.",
            "Je propose de partager. --- Давайте платить пополам.",
        ]
    },
    "Природа": {
        "Флора": [
            "un arbre --- дерево",
            "un buisson --- куст",
            "l'herbe --- трава",
            "la mousse --- мох",
            "une branche --- ветка",
            "un tronc --- ствол",
            "la racine --- корень",
            "une feuille --- лист",
            "un chêne --- дуб",
            "un bouleau --- береза",
            "un érable --- клен",
            "un saule --- ива",
            "un châtaignier --- каштан",
            "un cormier --- рябина",
            "un pin --- сосна",
            "un épicéa --- ель",
        ],
        "Цветы": [
            "une rose --- роза",
            "un iris --- ирис",
            "un tournesol --- подсолнух",
            "l'oreille-de-souris --- незабудка",
            "une marguerite --- ромашка",
            "une pivoine --- пион",
            "un narcisse --- нарцисс",
            "un perce-neige --- подснежник",
            "une orchidée --- орхидея",
            "une pensée --- анютины глазки",
            "un nénuphar --- кувшинка",
            "un crocus --- крокус",
            "un coquelicot --- мак",
            "une tulipe --- тюльпан",
            "un lilas --- сирень",
            "un pissenlit --- одуванчик",
        ],
        "Домашние животные": [
            "un cheval --- лошадь",
            "une brébis --- овца",
            "une vache --- корова",
            "un cochon --- свинья",
            "une poule --- курица",
            "un âne --- осел",
            "une oie --- гусь",
            "un canard --- утка",
            "une chèvre --- коза",
            "un chien --- собака",
            "un chat --- кот",
            "une dinde --- индюк",
            "un coq --- петух",
            "un lapin --- кролик",
            "un boeuf --- бык",
            "un poussin --- цыпленок",
        ],
        "Дикие и лесные животные": [
            "un cerf --- олень",
            "un crocodile --- крокодил",
            "un tigre --- тигр",
            "un loup --- волк",
            "un ours blanc --- белый медведь",
            "un lièvre --- заяц",
            "un hippopotame --- бегемот",
            "un renard --- лиса",
            "un pinguin --- пингвин",
            "un éléphant --- слон",
            "un lion --- лев",
            "un ours brun --- бурый медведь",
            "une girafe --- жираф",
            "un écureuil --- белка",
            "un kangourou --- кенгуру",
            "un hérisson --- еж",
        ],
        "Морские обитатели": [
            "une baleine --- кит",
            "une torpille --- скат",
            "un hippocampe --- морской конек",
            "un saumon --- лосось",
            "un dauphin --- дельфин",
            "un poulpe --- осьминог",
            "un thon --- тунец",
            "un morse --- морж",
            "un requin --- акула",
            "une étoile de mer --- морская звезда",
            "un congre --- морской угорь",
            "un crabe --- краб",
            "une tortue --- черепаха",
            "une méduse --- медуза",
            "un hérisson de mer --- морской еж",
            "une moule --- мидия",
        ],
        "Насекомые и паукообразные": [
            "une abeille --- пчела",
            "un bourdon --- шмель",
            "une blatte --- таракан",
            "un moustique --- комар",
            "une guêpe --- оса",
            "une libellule --- стрекоза",
            "une coccinelle --- божья коровка",
            "une sauterelle --- кузнечик",
            "un papillon --- бабочка",
            "une araignée --- паук",
            "une chenille --- гусеница",
            "un scorpion --- скорпион",
            "une fourmi --- муравей",
            "une scarabée --- жук",
            "une mouche --- муха",
            "une pyrale --- мотылек",
        ],
        "Поведение животных (глаголы и выражения)": [
            "hiberner --- быть в спячке",
            "mourir, disparaître --- вымирать",
            "ronger --- грызть",
            "jouer --- играть",
            "picoter --- клевать",
            "(жалить) piquer; (о животных) mordre --- кусать",
            "ruer, regimber --- лягнуть",
            "attaquer; se jeter sur --- нападать",
            "flairer --- нюхать (о животных)",
            "picorer (о птицах) --- отыскивать себе корм",
            "paître, pâturer --- пастись",
            "ramper --- ползать",
            "cacher --- прятать",
            "faire peur à --- пугать",
            "aller à gallop --- скакать галопом",
            "griffer --- царапать",
        ],
        "Издаваемые звуки (глаголы)": [
            "bêler --- блеять",
            "glapir --- визжать",
            "hurler --- выть",
            "bourdonner --- жужжать",
            "coasser --- квакать",
            "crier --- кричать",
            "cancaner, nasiller --- крякать",
            "aboyer --- лаять",
            "ronronner --- мурлыкать",
            "mugir, beugler --- мычать",
            "miauler --- мяукать",
            "guiorer --- пищать (о мышах)",
            "mugir, hurler --- реветь",
            "rugir; gronder (о собаке) --- рычать",
            "geindre --- скулить",
            "striduler (о кузнечикe) --- трещать",
            "grogner --- хрюкать",
            "siffler (о змеях, гусях) --- шипеть",
        ],
    },
    "Медицина": {
        "В больнице": [
            "un hôpital --- больница",
            "un docteur --- доктор",
            "une ambulance --- скорая помощь (карета)",
            "un microscope --- микроскоп",
            "une béquille --- костыль",
            "la goutte-à-goutte --- капельница",
            "le cardiogramme --- кардиограмма",
            "un scalpel --- скальпель",
            "la radio --- рентген",
            "un thermomètre --- градусник",
            "les analyses --- анализы",
            "un tensiomètre --- тонометр",
            "un chariot --- каталка",
            "une proctoclyse --- клизма",
            "une éprouvette --- пробиркa",
            "un stéthoscope --- стетоскоп",
        ],
        "Врачи и медперсонал": [
            "un obstétricien --- акушер (врач)",
            "une sage-femme --- акушерка",
            "un anesthésiologiste --- анестезиолог",
            "un vénéréologue --- венеролог",
            "un gastroentérologue --- гастроэнтеролог",
            "un gynécologue --- гинеколог",
            "un dermatologiste --- дерматолог",
            "un cardiologue --- кардиолог",
            "un dentiste --- стоматолог",
            "un orthophoniste --- логопед",
            "un masseur --- массажист",
            "un neuropathologue --- невропатолог",
            "un néonatologue --- неонатолог (врач новорожденных)",
            "un ophtalmologiste --- офтальмолог",
            "un cancérologue --- онколог",
            "un orthopédiste --- ортопед",
            "un oto-rhinolaryngologiste --- отоларинголог",
            "un pédiatre --- педиатр",
            "un psychiatre --- психиатр",
            "un pneumologue --- пульмонолог ",
            "un radiologiste --- радиолог, рентгенолог",
            "un rhumatologiste --- ревматолог",
            "un généraliste --- терапевт",
            "un urologue --- уролог",
            "une aide-médecin --- фельдшер",
            "un physiothérapeute --- физиотерапевт",
            "un chirurgien --- хирург",
            "un endocrinologue --- эндокринолог",
        ],
        "У врача: полезные фразы": {
            "_": [
                "À la réception --- В регистратуре",
                "À l'examen --- На обследовании",
                "La discussion des symptômes --- Обсуждение симптомов",
            ],
            "В регистратуре": [
                "Je voudrais voir le docteur. --- Я бы хотел попасть на прием к врачу.",
                "Vous venez sur rendez-vous? --- У вас назначено?",
                "Vous avez une assurance médicale? --- У вас есть медицинская страховка?",
                "Quand le docteur reçoit? --- Когда принимает врач?",
            ],
            "На обследовании": [
                "Où ça fait mal? — Ici. --- Где болит? — Тут болит.",
                "Je vais prendre votre tension /la température /le pouls. --- Я собираюсь измерить ваше давление / вашу температуру /ваш пульс.",
                "Ouvrez la bouche. Toussez. --- Откройте рот. Покашляйте.",
            ],
            "Обсуждение симптомов": [
                "Quels symptômes vous avez? --- Какие у вас симптомы?",
                "J'ai de la fièvre/j'ai mal à la gorge/des maux de tête/l'efflorescence. --- У меня температура / болит горло / головная боль / сыпь.",
                "J'ai vomi. --- Меня стошнило.",
                "J'ai mal aux lombes. --- У меня боль в пояснице.",
                "J'ai mal au dos. --- У меня боль в спине.",
                "Je me sens deprimé. --- Я чувствую себя подавленным.",
                "Je souffre d'insomnie. --- У меня бессонница.",
                "Vous avez une allergie? --- У вас есть на что-либо аллергия?",
                "Je suis allergique à... --- У меня аллергия на…",
                "Combien de temps je devrais prendre ce médicament? --- Как долго мне придется пить это лекарство?",
            ]
        },
        "Недомогания": [
            "le mal à l'estomac --- боль в желудке",
            "les maux de tête --- головная боль",
            "les brûlures d'estomac --- изжога",
            "le mal à l'oreille --- боль в ухе",
            "un vertige --- головокружение",
            "le rhumatisme --- ревматизм",
            "le mal à la gorge --- больное горло",
            "le mal de dents --- зубная боль",
            "la nausée --- тошнота",
        ],
        "Симптомы": [
            "la douleur/le mal --- боль",
            "la tension normale --- давление нормальное",
            "la perte d'appétit --- потеря аппетита",
            "la tension haute --- давление высокое",
            "une démangeaison --- зуд",
            "l'exanthème --- сыпь",
            "la tension basse --- давление низкое",
            "une hémorragie --- кровотечение",
            "l'obésité --- чрезмерный вес",
        ],
        "Болезни": [
            "une allergie --- аллергия",
            "une grippe --- грипп",
            "une indigestion --- несварение желудка",
            "une angine --- ангина",
            "une dépression --- депрессия",
            "une pneumonie --- пневмония",
            "un asthme --- астма",
            "une constipation --- запор",
            "un refroidissement --- простуда",
            "une insomnie --- бессонница",
            "une crise cardiaque --- инфаркт",
            "le cancer --- рак",
            "une bronchite --- бронхит",
            "un rhume --- насморк",
            "un ulcère --- язва",
        ],
        "В аптеке: лекарства и средства": [
            "l'ordonnance --- рецепт",
            "les médicaments --- лекарства",
            "une pharmacie --- аптека",
            "la poudre --- порошок",
            "les gouttes --- капли",
            "une seringue --- шприц",
            "l'iode --- йод",
            "un compte-gouttes --- пипетка",
            "un sirop --- сироп",
            "l'ouate --- вата",
            "un blister --- блистер",
            "des comprimés --- таблетки",
            "l'onguent --- мазь",
            "un sparadrap --- лейкопластырь",
            "un vaccin --- вакцина",
            "une bande --- бинт",
        ],
        "В аптеке: полезные фразы": [
            "Où se trouve la pharmacie de service? --- Где находится дежурная аптека?",
            "Avez-vous un médicament analogue? --- У вас есть заменитель этого лекарства?",
            "Est-ce que je peux acheter les antibiotiques sans prescription? --- Могу я купить антибиотики без рецепта врача?",
            "J'ai besoin de quelque chose contre le rhume et la tousse. J'ai mal à la gorge. --- Мне нужно что-то от кашля и насморка. У меня болит горло.",
            "J'ai besoin de quelque chose contre la grippe/le rhume/la fièvre. --- Мне нужно что-нибудь от гриппа / простуды / высокой температуры.",
            "Qu'avez-vous comme fébrifuge/vitamines/fortifiant/laxatif? --- Есть ли у вас жаропонижающее/витамины/общеукрепляющее/слабительное?",
            "Combien de fois par jour faut-il prendre ce médicament? --- Сколько раз в день нужно принимать это лекарство?",
            "Comment il faut le prendre? --- Как принимать это лекарство?",
            "Il faut le prendre après le repas/à jeun. --- Нужно его принимать после еды/натощак.",
            "Combien de comprimés? --- Сколько таблеток?",
            "Absorbez-le par une cuillère/une petite cuillère. --- Принимайте его по столовой/чайной ложке.",
            "Est-ce un médicament à usage interne ou externe? --- Это лекарства для внутреннего или наружного применения?",
            "Dans combien de temps cette potion sera prête? --- Когда будет готова эта микстура?",
        ],
    },
    "Почта и телефон": {
        "Почта и телефон": [
            "la poste --- почта",
            "une lettre --- письмо",
            "une enveloppe --- конверт",
            "un timbre --- марка",
            "la boîte aux lettres --- почтовый ящик",
            "un télégramme --- телеграмма",
            "le bureau de change --- обмен валют",
            "une carte postale --- открытка",
            "un colis --- посылка",
            "une estampille --- штемпель",
            "le virement --- денежный перевод",
            "un cachet de cire --- печать",
            "le récepteur --- трубка",
            "un téléphone --- телефон",
            "une cabine téléphonique --- телефонная кабина",
            "le code postale --- почтовый индекс",
        ],
        "Почта и телефон: полезные фразы": [
            "Où puis-je envoyer un colis postale/une lettre recommandée? --- Где я могу отправить посылку/заказное письмо?",
            "Je veux envoyer une lettre urgente. --- Я хочу отправить письмо экспресспочтой.",
            "Peut-on acheter douze timbres, s'il vous plaît? --- Можно купить двенадцать марок, пожалуйста?",
            "Je voudrais envoyer un virement. --- Я хочу отправить денежный перевод.",
            "La lettre en Russie, combien coûte-t-elle? --- Сколько стоит письмо в Россию?",
            "Combien coûte une carte postale? --- Сколько стоит открытка?",
            "Où peut-on recevoir ma lettre en poste restante? --- Где можно получить письмо до востребования?",
            "Quel est le tarif pour une lettre/une carte postale pour ...? --- Какой тариф на письмо/открытку до …?",
            "Je voudrais envoyer le fax à … --- Я хочу послать факс в …",
            "Combien de temps mettent les lettres pour ...? --- Сколько времени нужно, чтобы письма дошли до …?",
            "Combien d'argent faut-il payer? --- Сколько денег нужно заплатить?",
            "Je voudrais téléphoner à Moscou. --- Мне нужно позвонить в Москву.",
            "Le numéro (la ligne) est occupé(e). --- Номер занят (линия занята).",
            "Est-ce que je pourrais parler à …? --- Могу ли я поговорить с …?",
            "Vous vous trompez de numéro. --- Вы ошиблись номером.",
            "S'il vous plaît, refaites le numéro. --- Наберите еще раз, пожалуйста.",
            "Ne raccrochez pas! --- Не кладите трубку!",
            "Dites, que c'est ... qui a téléphoné … --- Передайте, что звонил(-а) …",
            "Je n'entends pas ce que vous dites. --- Я не слышу, что вы говорите.",
        ],
    },
    "Праздник": {
        "Праздник": [
            "un cadeau --- подарок",
            "un serpentin --- серпантин",
            "du champagne --- шампанское",
            "un anniversaire --- день рождения",
            "un gâteau --- торт",
            "un bouquet --- букет",
            "un cocktail --- коктейль",
            "une masque --- маска",
            "une guirlande --- гирлянда",
            "un feu d'artifice --- фейерверк",
            "les bonbons --- конфеты",
            "un bonnet de fête --- колпак",
            "un ballon --- шарики",
            "les félicitations --- поздравления",
            "la musique --- музыка",
            "les bougies --- свечи",
        ],
        "Музыкальные инструменты": [
            "un piano --- пианино",
            "un tambour --- барабан",
            "une trompette --- труба",
            "la violoncelle --- виолончель",
            "un violon --- скрипка",
            "un accordéon --- аккордеон",
            "un saxophone --- саксофон",
            "un tambourin --- бубен",
            "un archet --- смычок",
            "la guitare électrique --- электрогитара",
            "un piano à queue --- рояль",
            "une flûte --- флейта",
            "une guitare --- гитара",
            "un synthétiseur --- синтезатор",
            "une harpe --- арфа",
            "un microphone --- микрофон",
        ],
        "Французские праздники": [
            "Новый год --- Le Nouvel An / Le Jour de l'An (Le 1er janvier)",
            "Богоявление --- La fête des Rois / L'Epiphanie (Le 1er dimanche du janvier)",
            "Господне --- La Chandeleur Сретение (Le 2 février)",
            "День влюбленных --- La Saint-Valentin (Le 14 février)",
            "Масленицa --- Le Mardi Gras (Le 24 février)",
            "Международный женский день --- La Journée internationale des droits de la femme (Le 8 mars)",
            "День дурака / День смеха --- Le Рoisson d'avril (Le 1er avril)",
            "Пасха --- Pâques (Entre le 22 mars et le 25 avril)",
            "День труда --- La fête du travail (Le 1er mai)",
            "Окончание Второй мировой войны --- L'armistice de la deuxième guerre mondiale (Le 8 mai)",
            "Вознесение --- Pâques l'Ascension (Le jeudi, 40 jours après)",
            "День матери --- La fête des mères (A la fin du mois de mai)",
            "День Святой Троицы --- Pâques La Pentecôte (Le septième dimanche et le lundi après)",
            "День отца --- La fête des pères (Un dimanche vers la mi-juin)",
            "День музыки во Франции --- La fête de la musique (Le 21 juin)",
            "День взятия Бастилии --- Le 14 juillet: la fête nationale (Le 14 juillet)",
            "Успение Богородицы --- L'Assomption de la Vierge Marie (Le 15 août)",
            "Дни национального достояния --- Les Journées du Patrimoine (Le troisième week-end de septembre)",
            "День Всех Святых --- La Toussaint (Le 1er novembre)",
            "Праздник «Нового божоле» (вина) --- Le Beaujolais Nouveau (Le troisième jeudi de novembre)",
            "Рождество --- Le Noël (Le 25 décembre)",
        ],
        "Предлоги после глаголов": [
            "accuser de qch --- обвинять в ч.-л.",
            "avoir besoin de qch --- нуждаться в ч.-л.",
            "avoir envie de qch --- желать ч.-л.",
            "être fier de qn/qch --- гоpдиться ч.-л./к.-л.",
            "jouer de qch --- играть на ч.-л.",
            "manquer de qch --- не хватать ч.-л.",
            "mourir de qch --- умирать от ч.-л.",
            "parler de qch --- говорить о ч.-л.",
            "prendre soin de qn --- заботиться о ч.-л.",
            "remercier de qch --- благодарить за ч.-л.",
            "rêver de qch --- мечтать о ч.-л.",
            "s'occuper de qch --- заниматься ч.-л.",
            "se moquer de qn --- смеяться над к.-л.",
            "se plaindre de qch --- жаловаться на ч.-л.",
            "se souvenir de qch --- вспоминать о ч.-л.",
            "demander qch à qn --- просить ч.-л. у к.-л.",
            "dire qch à qn --- говорить ч.-л.",
            "donner qch à qn --- давать ч.-л.",
            "écrire qch à qn --- писать ч.-л.",
            "envoyer qch à qn --- отправлять ч.-л.",
            "faire attention à qch/qn --- обращать внимание на ч.-л./к.-л.",
            "interdire qch à qn --- запрещать ч.-л.",
            "jouer à qch --- играть во ч.-л.",
            "penser à qch/à qn --- думать о ч.-л.",
            "permettre qch à qn --- разрешать ч.-л.",
            "promettre qch à qn --- обещать ч.-л.",
            "proposer qch à qn --- предлагать ч.-л.",
            "répondre à qn --- отвечать к.-л.",
            "s'intéresser à qch --- интeресоваться ч.-л.",
            "téléphoner à qn --- звонить к.-л.",
        ],
    }
};
connaître
courir
partir
tôt --- рано, скоро
comme ça --- таким чином
souviens --- пам'ятати
se souviens --- згадувати